"""add_graph_fields_to_risk_analysis

Revision ID: 1fad31b3cef1
Revises: d3ebdce27c75
Create Date: 2026-07-18 22:04:46.484761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1fad31b3cef1'
down_revision: Union[str, None] = 'd3ebdce27c75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_risk_analysis', sa.Column('graph_score', sa.Float(), nullable=True))
    op.add_column('transaction_risk_analysis', sa.Column('graph_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('transaction_risk_analysis', sa.Column('graph_version', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction_risk_analysis', 'graph_version')
    op.drop_column('transaction_risk_analysis', 'graph_evidence')
    op.drop_column('transaction_risk_analysis', 'graph_score')
    # ### end Alembic commands ###
